### ISSUE TITLE
Modern way to "bring online"?

### ISSUE THREAD

**Issue by jamierajewski** [cern-fts/gfal2-util#2]
I noticed that the command to bring data online from tape storage is legacy, but there were no modern solutions/alternatives provided in the description. Is there a better way to achieve this, or is it still suggested to just use the legacy command? My only concern is that the legacy command may become deprecated in the future and disappear.

When we do transfers via the FTS, that has a `--bring-online` flag, but we only use that for moving bulk data between sites. Our collaborators use the gfal utilities to access data. Thanks!

**Comment by mpatrascoiu** [comment]
Hello,

Gfal2 will continue to support bringonline operations. Via the Gfal2 CLI tools, this is currently done via the `gfal-legacy-bringonline` command.

In the next `v1.8.0` release, we will rename `gfal-legacy-bringonline` command to `gfal-bringonline` as well as extend it's functionality to support operations on a list of files, read via an input file ([DMC-1208](https://its.cern.ch/jira/browse/DMC-1208)).

With the new release, I would advise you to switch to `gfal-bringonline`. The `gfal-legacy-bringonline` will continue to exist for some time before disappearing entirely.
