### ISSUE TITLE
renaming a directory to its own subdirectory deletes it instead

### ISSUE THREAD

**Issue by samtomguns** [cern-fts/gfal2-util#3]
gfal2-util 1.5.3

`gfal-rename /path/to/source /path/to/source/sub`

seems to permanently remove the source directory

**Comment by mpatrascoiu** [comment]
Hello,

I'm confused on what the expected result should be for this.
Linux `mv` would refuse this renaming.

Gfal2 creates a POSIX-like file object and sends the request to the server.
The servers I've tested (EOS via `root` and `https` protocols) refused this renaming.

What is the storage endpoint you've tried?

Cheers,
Mihai

**Comment by samtomguns** [comment]
Sorry for the confusion - you're right that it shouldn't work at all. I was just surprised when it deleted the entire directory rather than throw an error. I'll bring it up with our sysadmin first.
