### ISSUE TITLE
CommandRM doesn't run base.CommandBase.__init__

### ISSUE THREAD

**Issue by carmelopellegrino** [cern-fts/gfal2-util#4]
as per the issue title, the [`gfal2_util.rm.CommandRM`](https://github.com/cern-fts/gfal2-util/blob/develop/src/gfal2_util/rm.py#L32) class implements its own `__init__` method, which doesn't call that of the base class.

As a result, variables defined in the [`CommandBase.__init__` method](https://github.com/cern-fts/gfal2-util/blob/develop/src/gfal2_util/base.py#L81) are not initialized for `CommandRM` and, if the `gfal-rm` takes too long, it fails at line [178](https://github.com/cern-fts/gfal2-util/blob/develop/src/gfal2_util/base.py#L178) with the following exception:

```
Traceback (most recent call last):
  File "/bin/gfal-rm", line 37, in <module>
    sys.exit(Gfal2Shell().main(sys.argv))
  File "/usr/lib/python2.7/site-packages/gfal2_util/shell.py", line 74, in main
    return inst.execute(command_func)
  File "/usr/lib/python2.7/site-packages/gfal2_util/base.py", line 178, in execute
    if self.progress_bar is not None:
AttributeError: 'CommandRm' object has no attribute 'progress_bar'
```

I can provide a pull request to fix this issue.

Please, let me also know if you rather prefer this issue to be opened on CERN GitLab.

**Comment by mpatrascoiu** [comment]
Hello,

I'll have to look at the source of the error. Thanks for reporting!

If you already had a pull request in the works, that's great! You can send it here on Github, which ever is more convenient>

Cheers,
Mihai

**Comment by carmelopellegrino** [comment]
Dear Mihai,

sure, I've just submitted PR #5.

Cheers,
Carmelo

**Comment by carmelopellegrino** [comment]
Hi @mpatrascoiu, just to update on this issue and PR #5.
The fix is in production on INFN-T1 user interfaces since October 9th and no problems raised.

Are there any problems preventing #5 from merging?

**Comment by mpatrascoiu** [comment]
Hello Carmelo,

Thanks for the fix. It wasn't a problem wit the code, just finding the time to do this merge.
The change looks good, I've merged it into `develop` branch.

Turns out the problem was created when implementing [DMC-1222](https://its.cern.ch/jira/browse/DMC-1222).

Thanks for the contribution!

Cheers,
Mihai

**Comment by carmelopellegrino** [comment]
Dear Mihai,

thank you for your time!

Best regards,
Carmelo
